### PR TITLE
GSP-73: Organization Rename

### PR DESCRIPTION
**Pull request by JinnyYi**

### CODE REVIEW

**Comment by Xuanwo** [comment]
LGTM, let's rock!

This proposal will be merged before we release 4.0.

**Comment by JinnyYi** [comment]
@Xuanwo Could you help to update infra related?

**Comment by Xuanwo** [comment]
Got it, I will update them later this week.

**Comment by Xuanwo** [comment]
The infra migration has been done in https://forum.beyondstorage.io/t/service-maintenance-at-2021-05-21/42

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
